openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "API for foolish-plastic-model-shop app"
  description: "Demonstrates Swagger UI with Webpack"
servers:
  - url: "http://localhost:8000/"
    description: "Identity Server test API"
security:
  - identity_server_auth:
    - api
paths:
  /test:
    get:
      summary: "Runs a test request against the Identity Server demo API"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"